name: Main
on:
  push:
    branches-ignore:
      - 'releases/**'
    paths-ignore:
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
    - 'data/translations/**'
  pull_request:
    paths-ignore:
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
    - 'data/translations/**'
  workflow_dispatch:

jobs:
  Main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        include:
          - os: ubuntu-22.04
            CXXFLAGS: '-Wall -Wextra -pedantic -Werror'
    steps:
    - name: Clone repo
      uses: actions/checkout@v2.2.0
      with:
        submodules: recursive

    - name: Install dependent apt packages
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install qttools6-dev libpolkit-qt6-1-dev extra-cmake-modules

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --parallel 2
